// Building catalogue — the 20 structures of Metropolis, five categories, four tiers.
// Pure data, DOM-free. Numbers here are design starting points; src/balance/config.js
// may override any field per building (applied in index.js before registration).
//
// Per-unit fields: housing (citizens), jobs, income ($/s), powerGen / powerUse (MW),
// happiness (additive, civic curve), upkeep ($/s). `unlock(state, derived)` latches in core.
// `unlockAt` mirrors the unlock rule as data so the UI can show progress toward it.

export const CATEGORIES = [
  { id: 'residential', name: 'Residential', icon: '🏠', color: '#60a5fa', blurb: 'Homes. Citizens move in when there is room, power, and a reason to stay.' },
  { id: 'commercial', name: 'Commercial', icon: '🏪', color: '#4ade80', blurb: 'Shops and offices. Jobs for citizens, revenue for the treasury.' },
  { id: 'industrial', name: 'Industrial', icon: '🏭', color: '#fb923c', blurb: 'Heavy employers with heavy paychecks. The skyline gets a little hazier.' },
  { id: 'power', name: 'Power', icon: '⚡', color: '#facc15', blurb: 'Keep supply ahead of demand or the whole city dims.' },
  { id: 'civic', name: 'Civic', icon: '🏛️', color: '#c084fc', blurb: 'Parks, schools, and pride. Happy citizens grow faster and spend more.' },
];

const pop = (n) => (state) => (state?.res?.pop ?? 0) >= n;
const demand = (n) => (state, derived) => (derived?.powerDemand ?? 0) >= n;

export const BUILDINGS = [
  // ---------------------------------------------------------------- residential
  {
    id: 'house',
    name: 'Cottage',
    icon: '🏠',
    desc: 'A tidy starter home with a porch light and a lawn to mow.',
    category: 'residential',
    tier: 1,
    baseCost: 30,
    housing: 4,
    powerUse: 1,
    unlock: null,
    unlockHint: 'Available from the start',
  },
  {
    id: 'apartment',
    name: 'Apartment Block',
    icon: '🏢',
    desc: 'Six floors of neighbors who all know when you get home.',
    category: 'residential',
    tier: 2,
    baseCost: 400,
    housing: 24,
    powerUse: 6,
    unlock: pop(20),
    unlockAt: { pop: 20 },
    unlockHint: 'Reach 20 citizens',
  },
  {
    id: 'tower',
    name: 'Residential Tower',
    icon: '🏙️',
    desc: 'Glass and steel stacked skyward; the elevators hum all night.',
    category: 'residential',
    tier: 3,
    baseCost: 9000,
    housing: 160,
    powerUse: 40,
    unlock: pop(250),
    unlockAt: { pop: 250 },
    unlockHint: 'Reach 250 citizens',
  },
  {
    id: 'arcology',
    name: 'Arcology',
    icon: '🌆',
    desc: 'A city within the city, sealed against weather and small talk.',
    category: 'residential',
    tier: 4,
    baseCost: 1.2e6,
    housing: 2500,
    powerUse: 500,
    happiness: 0.02,
    unlock: pop(5000),
    unlockAt: { pop: 5000 },
    unlockHint: 'Reach 5,000 citizens',
  },

  // ----------------------------------------------------------------- commercial
  {
    id: 'shop',
    name: 'Corner Shop',
    icon: '🏪',
    desc: 'Coffee, newspapers, and gossip, open from dawn to whenever.',
    category: 'commercial',
    tier: 1,
    baseCost: 60,
    jobs: 5,
    income: 0.3,
    powerUse: 1,
    unlock: pop(4),
    unlockAt: { pop: 4 },
    unlockHint: 'Reach 4 citizens',
  },
  {
    id: 'office',
    name: 'Office Block',
    icon: '🏬',
    desc: 'Cubicles, fluorescent light, and very confident forecasts.',
    category: 'commercial',
    tier: 2,
    baseCost: 900,
    jobs: 40,
    income: 3,
    powerUse: 8,
    unlock: pop(60),
    unlockAt: { pop: 60 },
    unlockHint: 'Reach 60 citizens',
  },
  {
    id: 'mall',
    name: 'Shopping Mall',
    icon: '🛍️',
    desc: 'Fountains, a food court, and a parking lot visible from orbit.',
    category: 'commercial',
    tier: 3,
    baseCost: 20000,
    jobs: 300,
    income: 40,
    powerUse: 60,
    happiness: 0.01,
    unlock: pop(600),
    unlockAt: { pop: 600 },
    unlockHint: 'Reach 600 citizens',
  },
  {
    id: 'financial',
    name: 'Financial District',
    icon: '🏦',
    desc: 'Where the money is counted, then counted again, faster.',
    category: 'commercial',
    tier: 4,
    baseCost: 3e6,
    jobs: 4000,
    income: 900,
    powerUse: 800,
    unlock: pop(12000),
    unlockAt: { pop: 12000 },
    unlockHint: 'Reach 12,000 citizens',
  },

  // ----------------------------------------------------------------- industrial
  {
    id: 'factory',
    name: 'Factory',
    icon: '🏭',
    desc: 'Smokestacks and shift whistles. The town’s first real paycheck.',
    category: 'industrial',
    tier: 1,
    baseCost: 350,
    jobs: 20,
    income: 2.5,
    powerUse: 10,
    happiness: -0.02,
    unlock: pop(30),
    unlockAt: { pop: 30 },
    unlockHint: 'Reach 30 citizens',
  },
  {
    id: 'refinery',
    name: 'Refinery',
    icon: '⚗️',
    desc: 'Pipes, flare stacks, and sunsets that are suspiciously orange.',
    category: 'industrial',
    tier: 2,
    baseCost: 15000,
    jobs: 200,
    income: 60,
    powerUse: 120,
    happiness: -0.05,
    unlock: pop(800),
    unlockAt: { pop: 800 },
    unlockHint: 'Reach 800 citizens',
  },
  {
    id: 'techpark',
    name: 'Tech Campus',
    icon: '💻',
    desc: 'Ping-pong tables, free lunch, and a logo visible from the highway.',
    category: 'industrial',
    tier: 3,
    baseCost: 1.5e6,
    jobs: 2500,
    income: 1500,
    powerUse: 900,
    happiness: 0.02,
    unlock: pop(8000),
    unlockAt: { pop: 8000 },
    unlockHint: 'Reach 8,000 citizens',
  },

  // ---------------------------------------------------------------------- power
  {
    id: 'windmill',
    name: 'Windmill',
    icon: '🌬️',
    desc: 'Creaks in the breeze and keeps the porch lights burning.',
    category: 'power',
    tier: 1,
    baseCost: 120,
    powerGen: 6,
    unlock: (state, derived) => (derived?.powerDemand ?? 0) > 0,
    unlockAt: { powerDemand: 0.001 },
    unlockHint: 'Build something that draws power',
  },
  {
    id: 'coal',
    name: 'Coal Plant',
    icon: '🔥',
    desc: 'Cheap, reliable, and a little grimy. The lights stay on.',
    category: 'power',
    tier: 2,
    baseCost: 1500,
    jobs: 10,
    powerGen: 80,
    happiness: -0.03,
    unlock: demand(20),
    unlockAt: { powerDemand: 20 },
    unlockHint: 'Power demand reaches 20 MW',
  },
  {
    id: 'solar',
    name: 'Solar Farm',
    icon: '☀️',
    desc: 'Acres of panels tilting slowly to follow the sun.',
    category: 'power',
    tier: 3,
    baseCost: 25000,
    powerGen: 900,
    happiness: 0.01,
    unlock: pop(1000),
    unlockAt: { pop: 1000 },
    unlockHint: 'Reach 1,000 citizens',
  },
  {
    id: 'nuclear',
    name: 'Nuclear Plant',
    icon: '☢️',
    desc: 'Cooling towers on the skyline and a very thorough safety manual.',
    category: 'power',
    tier: 4,
    baseCost: 2e6,
    jobs: 100,
    powerGen: 25000,
    upkeep: 120,
    unlock: pop(10000),
    unlockAt: { pop: 10000 },
    unlockHint: 'Reach 10,000 citizens',
  },
  {
    id: 'fusion',
    name: 'Fusion Reactor',
    icon: '🌟',
    desc: 'A star in a bottle. The grid will never want for power again.',
    category: 'power',
    tier: 4,
    baseCost: 5e8,
    jobs: 200,
    powerGen: 2e6,
    happiness: 0.05,
    upkeep: 6000,
    unlock: (state) => (state?.res?.pop ?? 0) >= 100000 || (state?.prestige?.legacy ?? 0) >= 1,
    unlockAt: { pop: 100000, legacy: 1 },
    unlockHint: 'Reach 100,000 citizens, or found a new city',
  },

  // ---------------------------------------------------------------------- civic
  {
    id: 'park',
    name: 'City Park',
    icon: '🌳',
    desc: 'Benches, ducks, and a fountain someone keeps adding soap to.',
    category: 'civic',
    tier: 1,
    baseCost: 200,
    costGrowth: 1.2,
    happiness: 0.05,
    unlock: pop(15),
    unlockAt: { pop: 15 },
    unlockHint: 'Reach 15 citizens',
  },
  {
    id: 'school',
    name: 'School',
    icon: '🏫',
    desc: 'Bells, chalk dust, and the future learning long division.',
    category: 'civic',
    tier: 2,
    baseCost: 5000,
    costGrowth: 1.18,
    jobs: 30,
    powerUse: 5,
    happiness: 0.08,
    unlock: pop(300),
    unlockAt: { pop: 300 },
    unlockHint: 'Reach 300 citizens',
  },
  {
    id: 'hospital',
    name: 'Hospital',
    icon: '🏥',
    desc: 'Clean corridors and a helipad. The whole city sleeps easier.',
    category: 'civic',
    tier: 3,
    baseCost: 80000,
    costGrowth: 1.18,
    jobs: 200,
    powerUse: 50,
    happiness: 0.12,
    unlock: pop(2500),
    unlockAt: { pop: 2500 },
    unlockHint: 'Reach 2,500 citizens',
  },
  {
    id: 'stadium',
    name: 'Stadium',
    icon: '🏟️',
    desc: 'Eighty thousand voices under the floodlights on game night.',
    category: 'civic',
    tier: 4,
    baseCost: 5e6,
    costGrowth: 1.2,
    jobs: 500,
    income: 2000,
    powerUse: 300,
    happiness: 0.25,
    unlock: pop(20000),
    unlockAt: { pop: 20000 },
    unlockHint: 'Reach 20,000 citizens',
  },
];
